[[main]]
  identifier = "bannerlord"
  name = "Bannerlord"
  pre = "fa-flag"
  pageRef = "tags/bannerlord"
  weight = 10

[[main]]
  identifier = "bannerlord-mods"
  name = "Mods"
  parent = "bannerlord"
  pageRef = "tags/mods"
  weight = 10

[[main]]
  identifier = "bannerlord-guides"
  name = "Guides"
  parent = "bannerlord"
  pageRef = "tags/guide"
  weight = 20

[[main]]
  identifier = "bannerlord-help"
  name = "Help"
  parent = "bannerlord"
  pageRef = "tags/bannerlord-help"
  weight = 30

[[main]]
  identifier = "bannerlord-support"
  name = "Technical Support"
  parent = "bannerlord"
  pageRef = "tags/technical-support"
  weight = 40

[[main]]
  identifier = "warband"
  name = "Warband"
  pre = "fa-gavel"
  pageRef = "tags/bannerlord"
  weight = 20

[[main]]
  identifier = "warband-mods"
  name = "Mods"
  parent = "warband"
  pageRef = "tags/mods"
  weight = 10

[[main]]
  identifier = "warband-guides"
  name = "Guides"
  parent = "warband"
  pageRef = "tags/guide"
  weight = 20

[[main]]
  identifier = "warband-help"
  name = "Help"
  parent = "warband"
  pageRef = "tags/bannerlord-help"
  weight = 30

[[main]]
  identifier = "warband-support"
  name = "Technical Support"
  parent = "warband"
  pageRef = "tags/technical-support"
  weight = 40

[[main]]
  identifier = "mods"
  name = "Mods"
  pre = "fa-wrench"
  pageRef = "tags/mods"
  weight = 30

[[main]]
  identifier = "mods-mylittlewarband"
  name = "My Little Warband"
  parent = "mods"
  pageRef = "posts/bannerlord-my-little-warband-mod-for"
  weight = 10

[[main]]
  identifier = "mods-bannerlordmods"
  name = "Bannerlord Mods"
  parent = "mods"
  pageRef = "tags/bannerlord-mods"
  weight = 20

[[main]]
  identifier = "mods-modhelp"
  name = "Mod Help"
  parent = "mods"
  pageRef = "tags/mod-help"
  weight = 30

[[main]]
  identifier = "mods-allmods"
  name = "All Mods"
  parent = "mods"
  pageRef = "tags/mods"
  weight = 40

[[main]]
  identifier = "contact"
  name = "Contact US"
  pre = "fa-envelope"
  pageRef = "contact"
  weight = 40

[[main]]
  identifier = "about"
  name = "About"
  pre = "fa-info-circle"
  pageRef = "about"
  weight = 50

[[footer]]
  name = "About"
  pageRef = "about"
  weight = 10

[[footer]]
  name = "Contact"
  pageRef = "contact"
  weight = 20

[[footer]]
  name = "Privacy Policy"
  pageRef = "privacy-policy"
  weight = 30

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 40

[[footer]]
  name = "Categories"
  pageRef = "categories"
  weight = 50
